### ISSUE TITLE
Add ability to put all output files into one directory. 

### ISSUE THREAD

**Issue by HenryCWong** [ENCODE-DCC/hic-pipeline#115]
**Describe the solution you'd like**
Add the ability to have all the output files moved to one designated output file. I just ran 30 different hic jobs and combing through all of them with croo has been a pain. 

**Teachability, Documentation, Adoption, Migration Strategy**
Possibly an input flag or an optional input variable named "output" or something.

**Comment by leepc12** [comment]
Cromwell does not allow changing output directory structure.
Please let me know what part of `croo` is a pain. I will try to fix it.

**Comment by HenryCWong** [comment]
Ah neverminded I just realized croo had it's actually documentation on github. Didn't know it was it's own tool. 
I was was running croo without any flags and manually copying every single file based on the input file in the metadata and the file path in the .tsv file generated by croo. 

So now I have less problems. Another thing that could probably make life easier is if croo threw in some sort of thing that could identify the job that ran. The job id cromwell gives does not help me when I just ran 50 jobs and each one's results needs to be identifiable. So far I've had to look into the metadata and rename the job directory.

**Comment by leepc12** [comment]
The pipeline defaults to use this Croo definition JSON file.
https://raw.githubusercontent.com/ENCODE-DCC/hic-pipeline/dev/croo_out_def.json

I think you can make a copy of this and edit it to make your own output directory structure instead of parsing a TSV file generated from Croo.
```
croo ... --out-def-json YOUR_CROO_DEF_JSON_FILE
```

Modify a value under a key `path`. ${basename} is the basename of the output file.
For example, the BAM file will be copied (or soft-linked) on the directory `align/rep${i+1}/read_pair_${j+1}/`. `i` and `j` mean scatter loop indices or indices in output `Array[File]` type. In this example. `i` means replicate ID, `j` means read-end.
https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/hic.wdl#L71
```
{
  "hic.align": {
    "bam": {
      "path": "align/rep${i+1}/read_pair_${j+1}/${basename}",
```

**Comment by HenryCWong** [comment]
Thanks! I'll give it a try.

**Comment by paul-sud** [comment]
If you have a single replicate you can use the workflow option `"final_workflow_outputs_dir": "my-output-dir"`, you can see an example here: https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/tests/pytest_workflow_options.json .

It will copy all the outputs the specified directory. However, it will fail for multiple replicates due to name conflicts.
