### ISSUE TITLE
How does the pipeline utilize technical/biological replicates?

### ISSUE THREAD

**Issue by edsu7** [ENCODE-DCC/hic-pipeline#89]
Hi all,

I'm running analysis on ENCODE dataset that has biological replicates. My question is how does the pipeline handle replicates? What if I wanted to pool the replicates together?

Thanks,
Edmund

**Comment by paul-sud** [comment]
Hi Edmund,

The pipeline will first merge technical replicates within each biological replicate after alignment. It will then create a set of contacts independently for each biological replicate, pool the contact sets from _all_ biological replicates, and produce the `.hic` file representative of the entire experiment.

The replicate structure is determined by the `fastq` pipeline input. If you want to pool biological replicates then you just need to specify this input correctly. In the example below, copied from [the documentation](https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/docs/reference.md#input-descriptions), there are two biological replicates. The first biological replicate has two technical replicates, and the second biological replicate has just one technical replicate. Every technical replicate is comprised of a single set of paired fastqs.
```json
"hic.fastq": [
  [
    [
      "biorep1_techrep1_R1.fastq.gz",
      "biorep1_techrep1_R2.fastq.gz"
    ],
    [
      "biorep1_techrep2_R1.fastq.gz",
      "biorep1_techrep2_R2.fastq.gz"
    ]
  ],
  [
    [
      "biorep2_techrep1_R1.fastq.gz",
      "biorep2_techrep1_R2.fastq.gz"
    ]
  ]
]
```

I hope that helps, please let me know if something is unclear.

Best,

Paul

**Comment by edsu7** [comment]
Ah gotcha thats good to hear. Specifically my problem is that on their own the replicates are not deep enough for the arrow head step. 

I could run ignoring the flag or instead treat them as "technical" replicates. Libraries also do not share the same read size. Which would you recommend?

**Comment by paul-sud** [comment]
I'm not sure I'm following. When you say `on their own the replicates are not deep enough for the arrow head step`, I'm assuming that means you ran the pipeline individually for each biological replicate? In that case specifying the replicates together in a single pipeline might increase the number of detected contacts sufficiently for Arrowhead.

Or did you mean that you ran the pipeline once with all the biological replicates as input, and Arrowhead failed? In that case, converting those biological replicates to technical replicates is unlikely to increase the number of contacts in order to be able to run Arrowhead, and I would suggest that you ignore the flag if obtaining the Arrowhead domain calls is not critical. Domain calls from experiments with an insufficient number of contacts are not robust. If you must have domain calls, then you will need to find a more deeply sequenced experiment.

**Comment by edsu7** [comment]
Hi Paul, to clarify yes I did run the replicates individually. I will try them running both in a single pipeline and see where that gets me. 

Thanks for the help and insight.

Cheers,
Edmund
